name: Build UHeadless

on:
  push:
    branches: [ contrib ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Directory.Build.props'
      - '.editorconfig'
      - 'Nikcio.UHeadless.sln'
      - 'nuget.config'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ contrib ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: 'Directory.Packages.props'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./

      - name: Unit Tests
        run: dotnet run --verbosity normal
        working-directory: ./src/Nikcio.UHeadless.UnitTests

      - name: Integration Tests
        run: dotnet run --verbosity normal
        working-directory: ./src/Nikcio.UHeadless.IntegrationTests
