name: Build UHeadless

on:
  push:
    branches: [ "contrib" ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - '.editorconfig'
      - 'Nikcio.UHeadless.sln'
      - 'nuget.config'
      - '.github/workflows/build.yml'
      - '.release-please-config.json'
      - '.release-please-manifest.json'
  pull_request:
    branches: [ "contrib" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: 'Directory.Packages.props'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./
