name: Release to NuGet

on:
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: 'Directory.Packages.props'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./

    - name: Build
      run: dotnet build -c Release --no-restore /p:Version=${VERSION}
      working-directory: ./

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal /p:Version=${VERSION}
      working-directory: ./

    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output ./releases /p:Version=${VERSION}
      working-directory: ./

    - name: NuGet login
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push (Nikcio.UHeadless) to NuGet
      run: dotnet nuget push "Nikcio.UHeadless.${VERSION}.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
      working-directory: ./releases
